/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: scripts/generateImageBank.js
 * 
 * To regenerate, run: node scripts/generateImageBank.js
 */

// Image imports (must be static requires for React Native)
const images = {
  animals: require('../assets/bank/animals.webp'),
  business: require('../assets/bank/business.webp'),
  carparts: require('../assets/bank/carparts.webp'),
  cars: require('../assets/bank/cars.webp'),
  cats: require('../assets/bank/cats.webp'),
  comun: require('../assets/bank/comun.webp'),
  dogs: require('../assets/bank/dogs.webp'),
  food: require('../assets/bank/food.webp'),
  music: require('../assets/bank/music.webp'),
  nature: require('../assets/bank/nature.webp'),
  sports: require('../assets/bank/sports.webp'),
  travel: require('../assets/bank/travel.webp'),
  tv: require('../assets/bank/tv.webp'),
  vacations: require('../assets/bank/vacations.webp'),
  verbs: require('../assets/bank/verbs.webp'),
  videogames: require('../assets/bank/videogames.webp'),
};

// Image bank configuration
export const IMAGE_BANK = {
  animals: {
    image: images.animals,
    label: 'Animals',
    emoji: '🦁',
  },
  business: {
    image: images.business,
    label: 'Business',
    emoji: '💼',
  },
  carparts: {
    image: images.carparts,
    label: 'Carparts',
    emoji: '🔧',
  },
  cars: {
    image: images.cars,
    label: 'Cars',
    emoji: '🚗',
  },
  cats: {
    image: images.cats,
    label: 'Cats',
    emoji: '🐱',
  },
  comun: {
    image: images.comun,
    label: 'Comun',
    emoji: '📁',
  },
  dogs: {
    image: images.dogs,
    label: 'Dogs',
    emoji: '🐕',
  },
  food: {
    image: images.food,
    label: 'Food',
    emoji: '🍕',
  },
  music: {
    image: images.music,
    label: 'Music',
    emoji: '🎵',
  },
  nature: {
    image: images.nature,
    label: 'Nature',
    emoji: '🌿',
  },
  sports: {
    image: images.sports,
    label: 'Sports',
    emoji: '⚽',
  },
  travel: {
    image: images.travel,
    label: 'Travel',
    emoji: '✈️',
  },
  tv: {
    image: images.tv,
    label: 'Tv',
    emoji: '📺',
  },
  vacations: {
    image: images.vacations,
    label: 'Vacations',
    emoji: '📁',
  },
  verbs: {
    image: images.verbs,
    label: 'Verbs',
    emoji: '📁',
  },
  videogames: {
    image: images.videogames,
    label: 'Videogames',
    emoji: '📁',
  },
};

// Helper to get all image keys
export const getImageKeys = () => Object.keys(IMAGE_BANK);

// Helper to get image by key
export const getImageByKey = (key) => IMAGE_BANK[key]?.image || null;

// Helper to get emoji by key
export const getEmojiByKey = (key) => IMAGE_BANK[key]?.emoji || '📁';

export default IMAGE_BANK;
