/**
 * Script para generar automáticamente el banco de imágenes
 * 
 * USO: node scripts/generateImageBank.js
 * 
 * Este script lee la carpeta assets/bank/ y genera el código
 * de IMAGE_BANK automáticamente basándose en los archivos encontrados.
 */

const fs = require('fs');
const path = require('path');

// Configuración
const BANK_FOLDER = path.join(__dirname, '..', 'assets', 'bank');
const OUTPUT_FILE = path.join(__dirname, '..', 'utils', 'generatedImageBank.js');

// Emojis por defecto para categorías comunes
const EMOJI_MAP = {
    animals: '🦁',
    cats: '🐱',
    dogs: '🐕',
    pets: '🐾',
    food: '🍕',
    drinks: '🥤',
    travel: '✈️',
    business: '💼',
    music: '🎵',
    sports: '⚽',
    nature: '🌿',
    technology: '💻',
    computers: '🖥️',
    phones: '📱',
    art: '🎨',
    science: '🔬',
    health: '💊',
    medicine: '🩺',
    education: '📚',
    languages: '🗣️',
    home: '🏠',
    house: '🏡',
    fashion: '👗',
    weather: '🌤️',
    numbers: '🔢',
    colors: '🎨',
    family: '👨‍👩‍👧',
    body: '🧍',
    clothes: '👕',
    vehicles: '🚗',
    cars: '🚗',
    carparts: '🔧',
    automotive: '🚙',
    time: '⏰',
    emotions: '😊',
    feelings: '💭',
    jobs: '👷',
    work: '💼',
    school: '🏫',
    kitchen: '🍳',
    cooking: '👨‍🍳',
    bathroom: '🚿',
    bedroom: '🛏️',
    office: '🖥️',
    garden: '🌻',
    plants: '🌱',
    beach: '🏖️',
    ocean: '🌊',
    city: '🏙️',
    country: '🌄',
    hobbies: '🎮',
    games: '🎮',
    shopping: '🛒',
    restaurant: '🍽️',
    hospital: '🏥',
    bank: '🏦',
    money: '💰',
    airport: '✈️',
    movies: '🎬',
    tv: '📺',
    television: '📺',
    books: '📖',
    reading: '📚',
    writing: '✍️',
    love: '❤️',
    romance: '💕',
    space: '🚀',
    christmas: '🎄',
    halloween: '🎃',
    birthday: '🎂',
    party: '🎉',
    sleep: '😴',
    morning: '🌅',
    night: '🌙',
    winter: '❄️',
    summer: '☀️',
    spring: '🌸',
    autumn: '🍂',
    fall: '🍂',
};

// Función para capitalizar
const capitalize = (str) => str.charAt(0).toUpperCase() + str.slice(1);

// Función para obtener emoji
const getEmoji = (name) => EMOJI_MAP[name.toLowerCase()] || '📁';

// Leer archivos de la carpeta, prefiriendo WebP sobre PNG
function getImageFiles() {
    try {
        const files = fs.readdirSync(BANK_FOLDER);
        const imageFiles = files.filter(file =>
            /\.(png|jpg|jpeg|gif|webp)$/i.test(file)
        );

        // Crear un mapa para evitar duplicados (preferir WebP)
        const imageMap = new Map();
        for (const file of imageFiles) {
            const name = path.parse(file).name;
            const ext = path.parse(file).ext.toLowerCase();

            // Si ya existe, solo reemplazar si el nuevo es WebP
            if (imageMap.has(name)) {
                if (ext === '.webp') {
                    imageMap.set(name, file);
                }
            } else {
                imageMap.set(name, file);
            }
        }

        return Array.from(imageMap.values());
    } catch (error) {
        console.error('Error leyendo carpeta:', error.message);
        return [];
    }
}

// Generar código
function generateCode(files) {
    const imports = files.map(file => {
        const name = path.parse(file).name;
        return `  ${name}: require('../assets/bank/${file}'),`;
    }).join('\n');

    const bankEntries = files.map(file => {
        const name = path.parse(file).name;
        return `  ${name}: {
    image: images.${name},
    label: '${capitalize(name)}',
    emoji: '${getEmoji(name)}',
  },`;
    }).join('\n');

    return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: scripts/generateImageBank.js
 * 
 * To regenerate, run: node scripts/generateImageBank.js
 */

// Image imports (must be static requires for React Native)
const images = {
${imports}
};

// Image bank configuration
export const IMAGE_BANK = {
${bankEntries}
};

// Helper to get all image keys
export const getImageKeys = () => Object.keys(IMAGE_BANK);

// Helper to get image by key
export const getImageByKey = (key) => IMAGE_BANK[key]?.image || null;

// Helper to get emoji by key
export const getEmojiByKey = (key) => IMAGE_BANK[key]?.emoji || '📁';

export default IMAGE_BANK;
`;
}

// Main
function main() {
    console.log('🔍 Buscando imágenes en:', BANK_FOLDER);

    const files = getImageFiles();

    if (files.length === 0) {
        console.log('❌ No se encontraron imágenes en la carpeta bank');
        return;
    }

    console.log(`✅ Encontradas ${files.length} imágenes:`);
    files.forEach(f => console.log(`   - ${f}`));

    const code = generateCode(files);

    // Crear carpeta utils si no existe
    const utilsDir = path.dirname(OUTPUT_FILE);
    if (!fs.existsSync(utilsDir)) {
        fs.mkdirSync(utilsDir, { recursive: true });
    }

    fs.writeFileSync(OUTPUT_FILE, code);
    console.log(`\n📝 Archivo generado: ${OUTPUT_FILE}`);
    console.log('\n✨ ¡Listo! Ahora importa IMAGE_BANK desde utils/generatedImageBank.js');
}

main();
